name: Verify markdown links in Kyma project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  verify-links:
    strategy:
      fail-fast: false
      matrix:
        repository:
          - kyma
          - btp-manager
          - istio
          - serverless-manager
          - telemetry-manager
          - eventing-manager
          - api-gateway
          - nats-manager
          - application-connector-manager
          - keda-manager  
          - community
          - cloud-manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install 
        run: npm install
      - name: Checkout ${{matrix.repository}}
        uses: actions/checkout@v4
        with:
          repository: kyma-project/${{matrix.repository}}
          path: ${{matrix.repository}}
      - name: Verify links
        run: |
          cd ${{matrix.repository}}
          node ../md-check-link.js -q -n 8 -c ../.mlc.config.json ./